# Generated by Django 5.1.2 on 2024-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_posts', to='posts.tag'),
        ),
    ]
