# Generated by Django 5.2.4 on 2025-12-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rich_text', models.TextField(help_text='You can use basic HTML for formatting.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120)),
                ('subheadline', models.CharField(blank=True, max_length=240)),
                ('intro_rich_text', models.TextField(help_text='You can use basic HTML for formatting.')),
            ],
            options={
                'verbose_name': 'Site hero',
                'verbose_name_plural': 'Site hero',
            },
        ),
        migrations.CreateModel(
            name='AboutSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.aboutsection')),
            ],
        ),
    ]
